####################################
# Informacion de la aplicacion
####################################
spring.application.name=@project.name@
application-description=@project.description@
application-version=@project.version@
# Prefijo en la URL de la aplicación
server.servlet.context-path=/@project.name@

####################################
# ? Swagger / OpenAPI
####################################
# Ruta personalizada para Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html
# Ruta personalizada para los API docs
springdoc.api-docs.path=/api-docs
# Desactiva la respuesta generica para todos los endpoints
springdoc.override-with-generic-response=false

####################################
# Base de datos MySQL (principal)
####################################
# Estas propiedades definen la conexion por defecto a MySQL.
# En entorno Docker, se sobrescriben automaticamente con las variables
# definidas en docker-compose.yml (SPRING_DATASOURCE_*).
spring.datasource.url=jdbc:mysql://localhost:3306/bancodb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=banco_user
spring.datasource.password=banco_pass

# Dialecto y comportamiento de Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
# Cambiar a validate o none en producción
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

####################################
# Monitoreo con Actuator + Prometheus
####################################
# Expone solo los endpoints deseados
management.endpoints.web.exposure.include=health,info,prometheus
# Habilita exportación de metricas en formato Prometheus
management.metrics.export.prometheus.enabled=true
# Habilita el endpoint /actuator/prometheus
management.endpoint.prometheus.enabled=true
